In [1]:
import os 
import sys
import pandas as pd
import numpy as np  
from tqdm import tqdm
from typing import List



In [2]:

 ###################TODO: change the path to the correct one#####################

# action_****mode****.txt
path_to_label = '/Users/dennisbaumann/cars_paper/data/label_split/action_val.txt'
root_data = '/Users/dennisbaumann/cars_paper/data/'

n_frames_per_seq : int = 8

In [4]:
mode = 'val'
sample_root = root_data + f'val/obj_rt_{n_frames_per_seq}_{mode}/'

df = pd.read_csv(path_to_label, delimiter=' ')
print(df.head())    
ids : List[int] = df['id'].to_list()
paths : List[str] = df['path'].to_list()
action_labels : List[int] = df['action_label'].to_list()
start_acts : List[int] = df['start_act'].to_list()
end_acts : List[int] = df['end_act'].to_list()
start_frames : List[int] = df['start_frame'].to_list()
end_frames : List[int] = df['end_frame'].to_list()

print("Number of action sequences:", len(ids))

   id           path  action_label  start_act  end_act  start_frame  end_frame
0   1  subject3/k2/0            16         20      113            0        493
1   2  subject3/k2/0             8        141      218            0        493
2   3  subject3/k2/0            27        219      306            0        493
3   4  subject3/k2/0            30        397      493            0        493
4   5  subject3/k2/1            13         27      114            0        624
Number of action sequences: 122


In [5]:
os.makedirs(sample_root, exist_ok=True) # create the destination directory

sample_ids  = []
# sample the frames for each action
for i in tqdm(range(len(ids))):
    start_act = start_acts[i]
    end_act = end_acts[i]
    n_frames_total = end_act-start_act+1 # total number of frames in the action sequence
    assert n_frames_total >= n_frames_per_seq, \
        f"Requested {n_frames_per_seq} samples, but action (id {ids[i]}) has only {n_frames_total} frames"

    seq_ids = np.linspace(start_acts[i], end_acts[i], n_frames_per_seq, dtype=int)
    sample_ids.append(seq_ids)

sample_ids = np.array(sample_ids)
#np.save(sample_root + 'sample_ids.npy', sample_ids)
print("Sampling IDs shape:", sample_ids.shape) # sanity check the shape of the sampled ids
print("Last sampled sequence ids:", seq_ids) # sanity check the sampling from the last action

100%|██████████| 122/122 [00:00<00:00, 7496.19it/s]

Sampling IDs shape: (122, 8)
Last sampled sequence ids: [476 485 495 504 514 523 533 543]


In [6]:
print(sample_ids)

[[ 20  33  46  59  73  86  99 113]
 [141 152 163 174 185 196 207 218]
 [219 231 243 256 268 281 293 306]
 [397 410 424 438 451 465 479 493]
 [ 27  39  51  64  76  89 101 114]
 [141 148 156 164 171 179 187 195]
 [196 218 240 262 284 306 328 351]
 [358 374 391 407 424 440 457 474]
 [485 504 523 542 562 581 600 620]
 [ 27  38  49  61  72  84  95 107]
 [150 164 178 192 207 221 235 250]
 [256 284 312 340 368 396 424 452]
 [ 28  36  45  54  62  71  80  89]
 [115 123 131 139 147 155 163 172]
 [173 180 188 196 203 211 219 227]
 [228 242 256 270 284 298 312 326]
 [327 334 342 350 358 366 374 382]
 [387 422 457 492 527 562 597 632]
 [633 639 645 651 658 664 670 677]
 [678 689 701 712 724 735 747 759]
 [ 22  31  40  50  59  69  78  88]
 [113 121 129 137 145 153 161 169]
 [170 180 190 200 210 220 230 241]
 [251 263 275 287 300 312 324 337]
 [420 437 454 471 488 505 522 539]
 [ 15  26  38  50  61  73  85  97]
 [116 123 130 138 145 153 160 168]
 [195 204 213 222 231 240 249 259]
 [272 279 286 293 30

In [7]:
# manos : list[NDArray] = []
# cam_pose : list[NDArray] = []
# obj_pose : list[NDArray] = []
obj_rt = []
for i,id in enumerate(sample_ids):
    path = paths[i]
    # manos_list_curr = []
    # cam_pose_list_curr = []
    # obj_pose_list_curr = []
    obj_rt_list_curr = []
    for j in id:
        obj_rt_curr = np.loadtxt(root_data + path + f'/cam4/obj_pose_rt/{j:06d}.txt')
        obj_rt_list_curr.append(np.array(obj_rt_curr))
        ###################TODO: change the path to the correct one#####################
        # path_curr = '/Users/dennisbaumann/cars_paper/data/' + path + f'/cam4/hand_pose_mano/{j:06d}.txt'
        # cam_pose_curr = np.loadtxt('/Users/dennisbaumann/cars_paper/data/' + path + f'/cam4/cam_pose/{j:06d}.txt')
        # obj_pose_curr = np.loadtxt('/Users/dennisbaumann/cars_paper/data/' + path + f'/cam4/obj_pose/{j:06d}.txt')
        
        # mano_curr  = np.loadtxt(path_curr)
        # cam_pose_list_curr.append(np.array(cam_pose_curr))
        # manos_list_curr.append(np.array(mano_curr))
        # obj_pose_list_curr.append(np.array(obj_pose_curr))
    
    # manos.append(np.array(manos_list_curr))
    # cam_pose.append(np.array(cam_pose_list_curr))
    # obj_pose.append(np.array(obj_pose_list_curr))
    obj_rt.append(np.array(obj_rt_list_curr))
    print(np.shape(obj_rt))
    # print(np.shape(manos))
    # print(np.shape(cam_pose))



(1, 8, 17)
(2, 8, 17)
(3, 8, 17)
(4, 8, 17)
(5, 8, 17)
(6, 8, 17)
(7, 8, 17)
(8, 8, 17)
(9, 8, 17)
(10, 8, 17)
(11, 8, 17)
(12, 8, 17)
(13, 8, 17)
(14, 8, 17)
(15, 8, 17)
(16, 8, 17)
(17, 8, 17)
(18, 8, 17)
(19, 8, 17)
(20, 8, 17)
(21, 8, 17)
(22, 8, 17)
(23, 8, 17)
(24, 8, 17)
(25, 8, 17)
(26, 8, 17)
(27, 8, 17)
(28, 8, 17)
(29, 8, 17)
(30, 8, 17)
(31, 8, 17)
(32, 8, 17)
(33, 8, 17)
(34, 8, 17)
(35, 8, 17)
(36, 8, 17)
(37, 8, 17)
(38, 8, 17)
(39, 8, 17)
(40, 8, 17)
(41, 8, 17)
(42, 8, 17)
(43, 8, 17)
(44, 8, 17)
(45, 8, 17)
(46, 8, 17)
(47, 8, 17)
(48, 8, 17)
(49, 8, 17)
(50, 8, 17)
(51, 8, 17)
(52, 8, 17)
(53, 8, 17)
(54, 8, 17)
(55, 8, 17)
(56, 8, 17)
(57, 8, 17)
(58, 8, 17)
(59, 8, 17)
(60, 8, 17)
(61, 8, 17)
(62, 8, 17)
(63, 8, 17)
(64, 8, 17)
(65, 8, 17)
(66, 8, 17)
(67, 8, 17)
(68, 8, 17)
(69, 8, 17)
(70, 8, 17)
(71, 8, 17)
(72, 8, 17)
(73, 8, 17)
(74, 8, 17)
(75, 8, 17)
(76, 8, 17)
(77, 8, 17)
(78, 8, 17)
(79, 8, 17)
(80, 8, 17)
(81, 8, 17)
(82, 8, 17)
(83, 8, 17)
(84, 8, 17)
(

In [11]:
for n, pose in enumerate(obj_rt):
    np.save('/Users/dennisbaumann/cars_paper/data/val/obj_rt_8_val/' + f'{n:03d}.npy', pose)
